### ISSUE TITLE
can this library work like this？

### ISSUE THREAD

**Issue by MysteryRan** [gonzalonunez/Skeleton#1]
it's good way to load more data when users pull waiting the data callback, can this library  work？

**Comment by gonzalonunez** [comment]
Yes! That's the idea. The example project shows a `UITableView` populated with cells that use Skeleton to show the sliding gradient animations. You can just switch between displaying cells built like the ones in the example and your own cells to display the data.

**Comment by gonzalonunez** [comment]
I'm going to go ahead and close this issue -- let me know if you need anything else 👍
