### ISSUE TITLE
Add delay between transitions

### ISSUE THREAD

**Issue by MaciDE** [gonzalonunez/Skeleton#11]
First of all thanks for this great project!

Is it possible to add an delay between the transition. For now it seems to be an endless animation and I would like to add a small delay between each gradient.

**Comment by gonzalonunez** [comment]
Hi @MaciDE 👋

This is definitely possible! It's what the `group` parameter in `slide(_:_:)` is designed for. This will give you access to the `CAAnimationGroup` that's later added to the layer.

Your code will look something like this:

```swift
skeletonCell.slide(to: .right) { group in
  group.beginTime = CACurrentMediaTime() + 0.2
  return group
}
```

**Comment by gonzalonunez** [comment]
I'm not entirely sure about the delaying logic, you should double check that! Also, I'll probably change the function signature to `(CAAnimationGroup) -> Void` in the future.

**Comment by gonzalonunez** [comment]
Going to go ahead and close this issue, feel free to reopen it if you encounter any problems!
