### ISSUE TITLE
IB: Failed to render and update auto layout status.

### ISSUE THREAD

**Issue by lpbas** [gonzalonunez/Skeleton#15]
Hello. First of all I would like to thank you for this library. I am trying to use this library to build my skeleton loading views, but when I insert a single GradientContainerView, IB breaks,and nothing renders, resulting in all of my VCs being blank in the IB.

The error I get in the build log is the following:

```
file:///.../LoadingView.xib: error: IB Designables: Failed to render and update auto layout status for UIView (iN0-l3-epB): dlopen(Skeleton.framework, 1): no suitable image found.  Did find:
	Skeleton.framework: required code signature missing for 'Skeleton.framework'
```

I suppose, as the message says, that if I fix the signature problem then my views will render and there will not be any problems. Is this something I need to solve on my side, or there is a signing problem in the library itself? (Keep in mind that the project builds just fine, it's just that InterfaceBuilder is broken)

Thank you!

**Comment by gonzalonunez** [comment]
Hi! First off, thank you, and thanks to you for using the library! :)

Now, about this bug. How did you bring the framework into the project?

**Comment by lpbas** [comment]
I used CocoaPods. I have removed the library temporarily while I develop my app and will add it once I'm done using IB.

Any ideas/recommendations are appreciated!

**Comment by lpbas** [comment]
Hmm. It would seem like this library might not be the problem after all. I will need to take a deeper look into this.

After disabling Skeleton, other libraries were giving me the same error (GoogleMobileAds SDK for example) and after removing them and adding Skeleton back in, it works as expected with no errors. I'll close the issue and if I face the problem again I'll let you know. Thank you for the support :)
