### ISSUE TITLE
Migrate to Swift 4.2 ?

### ISSUE THREAD

**Issue by 10000TB** [gonzalonunez/Skeleton#16]

**Comment by gonzalonunez** [comment]
Will do! Sorry I've been slow to do this, completely forgot 😅

**Comment by 10000TB** [comment]
no worries !
Huge thanks for making this skeleton animation 👍  !

**Comment by taglia3** [comment]
Waiting for 4.2 support :)

**Comment by gonzalonunez** [comment]
On it! 🏃(Github being down for a while delayed this even further)

**Comment by gonzalonunez** [comment]
Resolved! `0.3.0` ✨
