### ISSUE TITLE
useing on loading data

### ISSUE THREAD

**Issue by MysteryRan** [gonzalonunez/Skeleton#2]
it's very wonderful to use this library when loading more data,  it's possible？

**Comment by gonzalonunez** [comment]
Yes! The example project shows a `UITableView` populated with cells that use Skeleton to show the sliding gradient animations. You can just switch between displaying cells built like the ones in the example and your own cells to display the data.

**Comment by MysteryRan** [comment]
you mean i will registe 2 styles cell including your style cell and mine? it's too troublesome,  you know the libiary called DZNEmptyDataSet, i mean when i use you library,. when i loading more data my last cell is your style, when loading finished,cell is my style

**Comment by gonzalonunez** [comment]
Something like that is exactly what I want to be able to do with this library but I'm not sure how to do it just yet. I have been thinking about the best way(s) to convert cells to their Skeleton equivalents. Unfortunately for now you'll have to create two separate cells.

**Comment by MysteryRan** [comment]
well if i find a good way, i will tell you a new loading style. thx

**Comment by gonzalonunez** [comment]
Awesome! I’ll be making an Issue about it soon. Thank you!
