### ISSUE TITLE
Animation stops working

### ISSUE THREAD

**Issue by fralways** [gonzalonunez/Skeleton#20]
When I put app to the background and then I return to it, animation with gradient stops working.
This happens on example project as well.

-my mistake sorry-

**Comment by trinhtranduc** [comment]
Hi, I got the same issue. Do you know how to fix it?

**Comment by gonzalonunez** [comment]
@trinhtranduc I have seen this before but never looked into it!

maybe @fralways can help debug here?

**Comment by gonzalonunez** [comment]
I believe there should be a way to fix this via the CAAnimation, and the library in its current state should give you access to everything you need to fix it.

**Comment by trinhtranduc** [comment]
@gonzalonunez Thank you for your response. I fixed this issue by adding:
`animGroup.isRemovedOnCompletion = false`  into function `func slide(to dir: SkeletonDirection, group: ((CAAnimationGroup) -> Void) = { _ in }) `
Thanks!
