### ISSUE TITLE
How can I make the animation like this using Skeleton?

### ISSUE THREAD

**Issue by huuchi207** [gonzalonunez/Skeleton#22]
I tried to make the animation like this: https://gph.is/g/amWgbvj (This one created by using library: https://github.com/dvtng/react-loading-skeleton in WebApp). 
I tried to chain animation from left to right, but I cant make the same length of gradient shape for all subview. Here is my code:
```
extension ShimmerExampleCell: SkeletonOwner {
    var gradientLayers: [CAGradientLayer] {
        return [imagePlaceholderView.gradientLayer, titlePlaceholderView.gradientLayer, subtitlePlaceholderView.gradientLayer]
    }
    func slide(to dir: SkeletonDirection, group: ((CAAnimationGroup) -> Void) = { _ in }) {
        imagePlaceholderView.gradientLayer.slide(to: .right) { (animationGroup) in
            animationGroup.beginTime = 0
        }
        
        titlePlaceholderView.gradientLayer.slide(to: .right) { (animationGroup) in
            animationGroup.beginTime = 1.1
            subtitlePlaceholderView.gradientLayer.add(animationGroup, forKey:  CAGradientLayer.kSlidingAnimationKey)
        }
    }
}
```
And I got:  https://gph.is/g/ZPgPlXV

Please help me. Thank you so much!

**Comment by gonzalonunez** [comment]
@huuchi207 Hi! So sorry I never responded to this, were you able to figure it out?

What I would personally do to solve this is:
1. Use a single `CAGradientLayer` with a single animation
2. Use another `CALayer` as its `.mask` on top, with the correct shape

Does that make sense? That way, you don't get any syncing problems between multiple layers etc. and you'll get the desired visual effect :)
