### ISSUE TITLE
Please support ios 8.

### ISSUE THREAD

**Issue by mhtranbn** [gonzalonunez/Skeleton#3]
Please support ios 8. Many thank @gonzalonunez  for suppports.!

**Comment by gonzalonunez** [comment]
Hey! So, `NSLayoutAnchor` is not supported on iOS 8 and this library uses them. Feel free to submit a PR that adds support for iOS 8 if you'd like to 👍 

If this issue gets enough requests I'll consider doing it myself. Cheers!

**Comment by mihailsalari** [comment]
Resolved
https://github.com/gonzalonunez/Skeleton/pull/5

**Comment by mihailsalari** [comment]
@gonzalonunez you're not an iOS Developer!!!
