### ISSUE TITLE
Cannot create circular GradientContainerView

### ISSUE THREAD

**Issue by sp71** [gonzalonunez/Skeleton#4]
**Issue**
Library does not support circular shimmer views

**Steps to Reproduce**
In the example project within _SkeletonCell.swift_, update the `imagePlaceholderView` to be a `GradientContainerView` and update  _SkeletonCell.xib_ with the changes. Run the example project to now see a square for the `imagePlaceholderView` with a shimmer. It seems the `imagePlaceholderView.layer.cornerRadius` is ignored if imagePlaceholderView is a `GradientContainerView`. 

**Image**
<img width="370" alt="screen shot 2017-05-21 at 9 56 39 am" src="https://cloud.githubusercontent.com/assets/6192130/26285803/d5a7f262-3e0b-11e7-8855-181747748d69.png">

**Comment by gonzalonunez** [comment]
Hey! Have you tried setting the layer's `masksToBounds` to `true`? I suspect that's the issue. Let me know if this works 🙂

**Comment by gonzalonunez** [comment]
If not, I'll take a look at it myself!

**Comment by sp71** [comment]
Yup, `masksToBounds` did the trick
