### ISSUE TITLE
Add support for Carthage

### ISSUE THREAD

**Issue by eneko** [gonzalonunez/Skeleton#7]
Seems like all needed to add support for [Carthage](https://github.com/Carthage/Carthage) is to mark your scheme as shared.

**Comment by gonzalonunez** [comment]
On it!

**Comment by gonzalonunez** [comment]
@eneko I _think_ Carthage should be supported now, I marked the [scheme](https://github.com/gonzalonunez/Skeleton/blob/master/Example/Pods/Pods.xcodeproj/xcshareddata/xcschemes/Skeleton.xcscheme) as shared. Let me know if this works?

**Comment by eneko** [comment]
Hey @gonzalonunez, could you make a 0.1.1 tag for testing?

**Comment by gonzalonunez** [comment]
@eneko Woops yep, just added it!

**Comment by eneko** [comment]
Works well. Muchas gracias!

For the `README`:

> Add this to your `Cartfile`:
> 
>     github "gonzalonunez/Skeleton" ~> 0.1.1

**Comment by gonzalonunez** [comment]
Ok awesome. Thanks for the README snippet!

De nada! 🙌🏻
